### ISSUE TITLE
Disabling the merit order also seems to disable fever

### ISSUE THREAD

**Issue by redekok** [quintel/mechanical_turk#128]
On the `deploy-feb-2019` branch I have worked on fixing the failing mechanical turk tests. By looking into the one concerning the input shares of the hybrid heat pump (https://github.com/quintel/mechanical_turk/blob/deploy-feb-2019/spec/demand/hybrid_heatpump_spec.rb#L94-L119) I observed that disabling the merit order function also seems to disable fever, for the following reasons:

- When I run the queries (`turk_hhp_network_gas_input_share`, etc.) in the sandbox, I observed that the shares do not increase/decrease at all when merit is _disabled_, despite the fact that the number of residences and insulation levels are changed in the model. When merit is _enabled_, I do get changes in the shares.

- To verify the assumption above, I checked whether the time resolved charts are displayed when merit is _disabled_. This didn't seem to be the case:

![screenshot 2019-02-27 at 12 19 10](https://user-images.githubusercontent.com/5946498/53486825-1e507d00-3a8a-11e9-8051-8e6af317c027.png)

@antw Does disabling merit indeed also disables fever?

**Comment by antw** [comment]
> @antw Does disabling merit indeed also disables fever?

This is correct. The setting name in the ETM is now rather misleading, and would be better labelled something like "Enable hourly load calculations". Turning off the merit order also disables Fever (dynamic heat) and dynamic hydrogen.

**Comment by redekok** [comment]
Thanks for your quick response. The test has started failing from January 30th; could it be the case that before this date it was _not_ the case that disabling merit also disabled fever? If so, I'm curious what made us change this. Do you have an answer on that, @antw?

**Comment by antw** [comment]
> The test has started failing from January 30th; could it be the case that before this date it was _not_ the case that disabling merit also disabled fever?

No, this hasn't changed recently. Disabling Merit has always disabled the other time-resolved calculations (largely because they depend on – or interact with – the calculations in the merit order). However, the heat and biomass projects were merged into ETEngine's master branch (beta) on Jan 29th, which likely explains why the tests then started failing.

It used to be the case that the inputs setting the number of [old](https://github.com/quintel/etsource/blob/d45e429c87cc312688c08f21796fb53e36c795f0/inputs/demand/households/households_misc/households_number_of_old_houses.ad) and [new](https://github.com/quintel/etsource/blob/d45e429c87cc312688c08f21796fb53e36c795f0/inputs/demand/households/households_misc/households_number_of_new_houses.ad) households did all kinds of magic, including setting the shares of electricity and gas in HHPs (which would be overwritten by Fever if time-resolved calculations were enabled). This seems no longer to be the case for the new "number_of_?_houses" inputs.

I think this is pretty reasonable; it is not common to turn off the merit order. Only about 4.5% of scenarios created this year have the MO disabled, and most are based on the old 80%/99% CO2 reduction presets.

---

Including @marliekeverweij @ChaelKruip

**Comment by redekok** [comment]
@marliekeverweij @ChaelKruip Do you know if it has been a conscious choice to omit setting the shares of electricity and gas in HHPs in the new `households_number_of_apartments.ad`, etc. files? If so, what was the underlying motivation?

**Comment by ChaelKruip** [comment]
> Do you know if it has been a conscious choice to omit setting the shares of electricity and gas in HHPs in the new `households_number_of_apartments.ad`, etc. files?

Not for me no.

**Comment by marliekeverweij** [comment]
I actually never exactly understood why the `number_of_?_houses` had influence on the shares of electricity and gas in HHPs. Why was this implemented @ChaelKruip?

We could add the magic again to the "number_of_?_houses" inputs, but I was actually happy to get rid of it!

Non-related question: 
Why is it actually possible to turn off the merit order? What is the use case?

**Comment by redekok** [comment]
@michieldenhaan Do you happen know why the `number_of_?_houses.ad` files were setting the input shares of electricity and gas in HHPs in the past?

**Comment by michieldenhaan** [comment]
Judging from the MT test the logic is probably that if insulation increases the gas part of the HHP is/can be used less often and hence the gas share goes down, the electricity + ambient part goes up. However, I don't know when this was implemented.

I'm in favour of not adding this back to the inputs, given that it's a bit murky and not many users disable Merit

**Comment by redekok** [comment]
The MT test is adjusted to these changes (i.e., merit order is enabled for the test regarding HHP carrier shares). Closing this issue.
