### ISSUE TITLE
Why is the etflex heat-pump add-on spec failing?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/mechanical_turk#71]
This probably has to do with the latest cost update.

**Comment by jorisberkhout** [comment]
The failing spec is caused by the fact that the heat-pump add-on was made demand drive in quintel/etsource@92edfe8c57da1cb7c6ed16086276e5708eb12978. This commit (amongst others) was merged into the master branch on May 15, explaining why the turk started reporting failed builds from then on.

Assigning to @ChaelKruip as he changed the behaviour of the heat-pump add-on to demand driven.

**Comment by ChaelKruip** [comment]
I think the reason is that the add-on heat pump runs for more FLH because it is now demand-driven. More FLH imply more fuel, hence the rise in cost. There is no real reason why we would expect add-on heat pumps to be cheaper in use than the other heating options.

I have changed the spec in https://github.com/quintel/mechanical_turk/commit/64ffa264b4d3288ae31dccbc00686757175350e7
